---
title: "NFL Player Career Longevity"
author: "Imogen, Adam and Nolan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
status <- read.csv("status.csv")

```

```{r}
library(dplyr)
library(tidyverse)
```


```{r}
all_seasons <- read.csv("NFL Player Stats(1922 - 2022).csv")
head(all_seasons)
seasons <- all_seasons[all_seasons$Season >= 2006,] #only have injury data from 2006 onwards
seasons <- seasons %>%
  select(Tm, Season, Player, Age, Pos, G, GS, AllTD, Pts, FGM, FGA)
head(seasons)
dim(seasons)
all_injuries <- read.csv("totalConcussion.csv") #injury and concussion by player and year
all_injuries <-  all_injuries %>% separate(Player, into = c("FirstName", "LastName"), sep = " ")
all_injuries <- all_injuries[all_injuries$Position != 'Position',]

#clean seasons
seasons <-  seasons %>% separate(Player, into = c("FirstName", "LastName"), sep = " ")
seasons$LastName <- gsub("\\+$", "", seasons$LastName)
seasons <-  seasons %>% mutate(AllTD = ifelse(is.na(AllTD),0, AllTD))


```


```{r Clean Position Col}
seasons <- seasons %>%
  mutate(Pos = ifelse(Pos %in% c("LCB", "CB", "RCB", "RCB/LCB", "DB/RCB", "RCB/LCB/DB", "LCB/RCB", "DB/LCB", "RCB/DB",
                                 "SS", "FS", "SS/FS", "LCB/FS", "DB/FS", "FS/SS", "SS/RLB", "S", "DB"), "DB", Pos))

seasons <- seasons %>%
  mutate(Pos = ifelse(Pos %in% c("MLB", "ROLB", "LLB/ROLB", "RLB", "RLB/MLB", "LOLB", "LLB", "LILB", "LB", "LILB/ROL", 
                                 "RILB", "LLB/RLB", "LB/LLB", "LLB/MLB", "LILB/RIL", "ROLB/LOL", "OLB", "MLB/RLB"), "LB", Pos))

seasons <- seasons %>%
  mutate(Pos = ifelse(Pos %in% c("LT/RT", "RT/LT", "LT", "T", "NT", "RT"), "T", Pos))

seasons <- seasons %>%
  mutate(Pos = ifelse(Pos %in% c("LDT/RDT", "LDT", "DT", "DT/LDT", "RDT", "DL"), "DT", Pos))

seasons <- seasons %>%
  mutate(Pos = ifelse(Pos %in% c("RDE/LDE", "RDE", "DE", "LDE/RDE", "LDE"), "DE", Pos))

seasons <- seasons %>%
  mutate(Pos = ifelse(Pos %in% c("LG", "G"), "G", Pos))

seasons <- seasons %>%
  mutate(Pos = ifelse(Pos %in% c("C/LG"), "C", Pos))

seasons <- seasons %>%
  mutate(Pos = ifelse(Pos %in% c("RB/TE", "FB", "DT/FB"), "FB", Pos))

seasons <- seasons %>%
  mutate(Pos = ifelse(Pos %in% c("QB", "WR/QB"), "QB", Pos))

all_injuries <- all_injuries %>%
  mutate(Position = ifelse(Position %in% c("CB", "DB", "S"), "DB", Position))

seasons <- seasons[seasons$Pos != "",]
all_injuries <- all_injuries[all_injuries$Position != "LS",]
all_injuries <- all_injuries[all_injuries$Position != "KR",]
all_injuries <- all_injuries[all_injuries$Position != "PR",]

sort(unique(all_injuries$Position))
sort(unique(seasons$Pos))


```


```{r Clean Team Col}

seasons$Team <- seasons$Tm

InjuriesSeason <- inner_join(all_injuries, seasons, by = "Team")

class(all_injuries$Team)
patterns <- c("Seahawks","Steelers", "Cowboys", "Lions", "Browns",       
"Chiefs","Dolphins","Eagles", "Buccaneers", "Vikings", "Saints", "Packers",
"Colts", "Falcons", "Bengals","Raiders", "Broncos", "Ravens", "Commanders",
"Giants", "49ers", "Jets", "Jaguars", "Panthers", "Bears", "Texans", "Patriots",
"Rams", "Chargers", "Titans", "Bills", "Cardinals", "Football Team", "Redskins",
"Niners")
replacements <- c("SEA", "PIT", "DAL", "DET", "CLE", "KAN", "MIA", "PHI",
              "TAM", "MIN", "NOR", "GNB", "IND", "ATL", "CIN", "LVR",
              "DEN", "BAL", "WAS", "NYG", "SFO", "NYJ", "JAX", "CAR", "CHI",
              "HOU", "NWE", "LAR", "LAC", "TEN", "BUF", "ARI", "WAS", "WAS", "SFO")
for (i in 1:length(patterns)) {
  all_injuries$Team <- gsub(patterns[i], replacements[i], all_injuries$Team)
}

head(all_injuries)

```


```{r Make the PlayerIDs}
#make injury ID to merge
all_injuries$PlayerID <- paste0(paste0(paste0(substring(all_injuries$FirstName, 1, 1), all_injuries$LastName), all_injuries$Position), all_injuries$Season)

#make season ID to merge
seasons$PlayerID <- paste0(paste0(paste0(substring(seasons$FirstName, 1, 1), seasons$LastName), seasons$Pos), seasons$Season)

#make status ID to merge
status$PlayerID <- paste0(paste0(paste0(substring(status$FirstName, 1, 1), status$LastName), status$Pos), status$Season)
```


```{r}
#MERGE ON INJURIES AND SEASONS
injuries <-  all_injuries %>% select(PlayerID, TotalInjuryCount, ConcussionTotal)
seasons2010 <- seasons[seasons$Season >= 2010,] %>% select(-Tm)
joined <- left_join(seasons2010, injuries, by = 'PlayerID')
joined <- joined %>% mutate(ConcussionTotal = ifelse(is.na(ConcussionTotal),0, ConcussionTotal))
joined <- joined %>% mutate(TotalInjuryCount = ifelse(is.na(TotalInjuryCount),0, TotalInjuryCount))

head(joined)
```


```{r Make final dataset}
#Making cumulative cols and response var
final <- joined
final <- final %>%
  group_by(FirstName, LastName, Pos) %>%
  arrange(Season) %>%
  mutate(G = cumsum(G), GS = cumsum(GS), AllTD = cumsum(AllTD), Pts = cumsum(Pts),
         FGM = cumsum(FGM), FGA = cumsum((FGA)), ConcussionTotal = cumsum(ConcussionTotal), TotalInjuryCount = cumsum(TotalInjuryCount))


#create response
final <- final %>% group_by(FirstName, LastName, Pos) %>%
  arrange(Season)%>% mutate(YearsRemaining = max(Season) - Season)

head(final)


#drop players that moved around a lot
final[final$Team != '3TM',]
final[final$Team != '2TM',]


#look at individual
final[final$LastName == 'Folk',]


kickers_final <- final[final$Pos == 'K',]
final <- final[final$Pos != 'K',] %>% select(-FGM, -FGA)
summary(final)


final_1 <- final
final_1$FiveYrLeft <- ifelse(final_1$YearsRemaining >= 5, 1 ,0)
final_1 <- final_1 %>% select(-YearsRemaining)
```

```{r}
library(caret)

set.seed(123)
train_index <- createDataPartition(final$YearsRemaining, p = 0.8, list = FALSE)
train_data <- final[train_index, ]
test_data <- final[-train_index, ]

# Check the dimensions
dim(train_data)
dim(test_data)


# Ensure YearsRemaining is numeric
train_data$YearsRemaining <- as.numeric(as.character(train_data$YearsRemaining))
train_data$YearsRemaining <- as.numeric(as.character(train_data$YearsRemaining))

names(final)

train_dataRB <- train_data[train_data$Pos == 'RB',] 
train_dataRB<- train_dataRB %>% ungroup() %>% select(YearsRemaining,Age, G, GS, AllTD, Pts, TotalInjuryCount, ConcussionTotal)

test_dataRB <- test_data[test_data$Pos == 'RB',]
test_dataRB<- test_dataRB %>% ungroup() %>% select(YearsRemaining, Age, G, GS, AllTD, Pts, TotalInjuryCount, ConcussionTotal)

linearRB <- lm(YearsRemaining ~ ., train_dataRB)


# Get predictions with 95% confidence intervals
predictions <- predict(linearRB, newdata = test_dataRB)
intervals <- predictions
intervals$lwr <- predictions - 2
intervals$upp <- predictions + 2
intervals_1 <- ifelse(test_dataRB$YearsRemaining >= intervals$lwr & test_dataRB$YearsRemaining <= intervals$upp, 1, 0)
sum(intervals_1)/length(intervals_1)


```

```{r}
library(caret)

set.seed(123)
train_index <- createDataPartition(final_1$FiveYrLeft, p = 0.8, list = FALSE)
train_data <- final_1[train_index, ]
test_data <- final_1[-train_index, ]

# Check the dimensions
dim(train_data)
dim(test_data)


# Ensure as.factor(train_data$FiveYrLeft)
train_data$FiveYrLeft <- as.numeric(train_data$FiveYrLeft)
test_data$FiveYrLeft <- as.numeric(test_data$FiveYrLeft)

names(final)

train_dataRB <- train_data[train_data$Pos == 'RB',] 
train_dataRB<- train_dataRB %>% ungroup() %>% select(FiveYrLeft,Age, G, GS, AllTD, Pts, TotalInjuryCount, ConcussionTotal)

test_dataRB <- test_data[test_data$Pos == 'RB',]
test_dataRB<- test_dataRB %>% ungroup() %>% select(FiveYrLeft, Age, G, GS, AllTD, Pts, TotalInjuryCount, ConcussionTotal)

linearRB <- glm(FiveYrLeft ~ ., train_dataRB, family = "binomial")


# Get predictions with 95% confidence intervals
predictions <- predict(linearRB, newdata = test_dataRB, type = "response")

test_pred <- ifelse(is.na(predictions), NA, ifelse(predictions > 0.5, 1, 0))

ifelse(test_dataRB$YearsRemaining >= data.frame(predictions)$lwr & test_dataRB$YearsRemaining <= data.frame(predictions)$upr, 1, 0)


```




